package com.jiangKlijna.web.dao;

import com.jiangKlijna.web.bean.Article;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    Article selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int updateByPrimaryKey(Article record);
}