package com.jiangKlijna.web.dao

import com.jiangKlijna.web.bean.Comment
import com.jiangKlijna.web.bean.VComment
import org.apache.ibatis.annotations.Param

interface CommentMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_comment

	 * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
	 */
	fun deleteByPrimaryKey(id: Int?): Int

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_comment

	 * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
	 */
	fun insert(record: Comment): Int

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_comment

	 * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
	 */
	fun insertSelective(record: Comment): Int

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_comment

	 * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
	 */
	fun selectByPrimaryKey(id: Int?): Comment

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_comment

	 * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
	 */
	fun updateByPrimaryKeySelective(record: Comment): Int

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_comment

	 * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
	 */
	fun updateByPrimaryKey(record: Comment): Int

	fun listByArticle(@Param("articleid") articleid: Int, @Param("limit") limit: Int, @Param("offset") offset: Int): List<VComment>
}