package com.jiangKlijna.web.dao;

import com.jiangKlijna.web.bean.Comment;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    Comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int updateByPrimaryKey(Comment record);
}