package com.jiangKlijna.web.dao;

import com.jiangKlijna.web.bean.FollowSubject;

public interface FollowSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_follow_subject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_follow_subject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int insert(FollowSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_follow_subject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int insertSelective(FollowSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_follow_subject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    FollowSubject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_follow_subject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(FollowSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_follow_subject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int updateByPrimaryKey(FollowSubject record);
}