package com.jiangKlijna.web.dao;

import com.jiangKlijna.web.bean.FollowUser;

public interface FollowUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_follow_user
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_follow_user
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int insert(FollowUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_follow_user
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int insertSelective(FollowUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_follow_user
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    FollowUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_follow_user
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(FollowUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_follow_user
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int updateByPrimaryKey(FollowUser record);
}