package com.jiangKlijna.web.dao

import com.jiangKlijna.web.bean.Message

interface MessageMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_message

	 * @mbg.generated Thu Jul 27 18:15:24 CST 2017
	 */
	fun deleteByPrimaryKey(id: Int?): Int

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_message

	 * @mbg.generated Thu Jul 27 18:15:24 CST 2017
	 */
	fun insert(record: Message): Int

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_message

	 * @mbg.generated Thu Jul 27 18:15:24 CST 2017
	 */
	fun insertSelective(record: Message): Int

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_message

	 * @mbg.generated Thu Jul 27 18:15:24 CST 2017
	 */
	fun selectByPrimaryKey(id: Int?): Message

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_message

	 * @mbg.generated Thu Jul 27 18:15:24 CST 2017
	 */
	fun updateByPrimaryKeySelective(record: Message): Int

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_message

	 * @mbg.generated Thu Jul 27 18:15:24 CST 2017
	 */
	fun updateByPrimaryKey(record: Message): Int
}