package com.jiangKlijna.web.dao;

import com.jiangKlijna.web.bean.Subject;

public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_subject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_subject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_subject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int insertSelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_subject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    Subject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_subject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_subject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    int updateByPrimaryKey(Subject record);
}