package com.jiangKlijna.web.dao

import com.jiangKlijna.web.bean.Subject
import com.jiangKlijna.web.bean.VArticle
import com.jiangKlijna.web.bean.VSubject
import org.apache.ibatis.annotations.Param

interface SubjectMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_subject

	 * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
	 */
	fun deleteByPrimaryKey(id: Int?): Int

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_subject

	 * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
	 */
	fun insert(record: Subject): Int

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_subject

	 * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
	 */
	fun insertSelective(record: Subject): Int

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_subject

	 * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
	 */
	fun selectByPrimaryKey(id: Int?): Subject

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_subject

	 * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
	 */
	fun updateByPrimaryKeySelective(record: Subject): Int

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table blog_subject

	 * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
	 */
	fun updateByPrimaryKey(record: Subject): Int

	fun findSubjectByTitle(title: String): Subject?

	fun findById(id: Int): VSubject

	fun listByIndex(@Param("limit") limit: Int, @Param("offset") offset: Int): List<VSubject>

	fun listBySearch(@Param("limit") limit: Int, @Param("offset") offset: Int, @Param("search") search: String): List<VSubject>

	fun listByFollow(@Param("limit") limit: Int, @Param("offset") offset: Int, @Param("username") username: String): List<VSubject>

}