package com.jiangKlijna.web.dao

import com.jiangKlijna.web.bean.User

interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    fun deleteByPrimaryKey(id: Int?): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    fun insert(record: User): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    fun insertSelective(record: User): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    fun selectByPrimaryKey(id: Int?): User

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    fun updateByPrimaryKeySelective(record: User): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    fun updateByPrimaryKey(record: User): Int

    fun findByUser(u: User): Long?

    fun findByUsername(username: String): Long?
}