package com.jiangKlijna.web.bean;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.title
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.content
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.userid
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.subjectid
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer subjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.favoritenumber
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer favoritenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.seenumber
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer seenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Long createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.id
     *
     * @return the value of blog_article.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.id
     *
     * @param id the value for blog_article.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.title
     *
     * @return the value of blog_article.title
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.title
     *
     * @param title the value for blog_article.title
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.content
     *
     * @return the value of blog_article.content
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.content
     *
     * @param content the value for blog_article.content
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.userid
     *
     * @return the value of blog_article.userid
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.userid
     *
     * @param userid the value for blog_article.userid
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.subjectid
     *
     * @return the value of blog_article.subjectid
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.subjectid
     *
     * @param subjectid the value for blog_article.subjectid
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.favoritenumber
     *
     * @return the value of blog_article.favoritenumber
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getFavoritenumber() {
        return favoritenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.favoritenumber
     *
     * @param favoritenumber the value for blog_article.favoritenumber
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setFavoritenumber(Integer favoritenumber) {
        this.favoritenumber = favoritenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.seenumber
     *
     * @return the value of blog_article.seenumber
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getSeenumber() {
        return seenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.seenumber
     *
     * @param seenumber the value for blog_article.seenumber
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setSeenumber(Integer seenumber) {
        this.seenumber = seenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.createtime
     *
     * @return the value of blog_article.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.createtime
     *
     * @param createtime the value for blog_article.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }
}