package com.jiangKlijna.web.bean

class Article {
    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.id

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.id

     * @return the value of blog_article.id
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.id

     * @param id the value for blog_article.id
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var id: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.title

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.title

     * @return the value of blog_article.title
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.title

     * @param title the value for blog_article.title
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var title: String? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.content

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.content

     * @return the value of blog_article.content
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.content

     * @param content the value for blog_article.content
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var content: String? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.userid

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.userid

     * @return the value of blog_article.userid
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.userid

     * @param userid the value for blog_article.userid
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var userid: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.subjectid

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.subjectid

     * @return the value of blog_article.subjectid
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.subjectid

     * @param subjectid the value for blog_article.subjectid
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var subjectid: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.favoritenumber

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.favoritenumber

     * @return the value of blog_article.favoritenumber
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.favoritenumber

     * @param favoritenumber the value for blog_article.favoritenumber
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var favoritenumber: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.seenumber

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.seenumber

     * @return the value of blog_article.seenumber
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.seenumber

     * @param seenumber the value for blog_article.seenumber
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var seenumber: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.createtime

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.createtime

     * @return the value of blog_article.createtime
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.createtime

     * @param createtime the value for blog_article.createtime
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var createtime: Long? = null
}