package com.jiangKlijna.web.bean;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.content
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.userid
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.articleid
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer articleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Long createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.id
     *
     * @return the value of blog_comment.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.id
     *
     * @param id the value for blog_comment.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.content
     *
     * @return the value of blog_comment.content
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.content
     *
     * @param content the value for blog_comment.content
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.userid
     *
     * @return the value of blog_comment.userid
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.userid
     *
     * @param userid the value for blog_comment.userid
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.articleid
     *
     * @return the value of blog_comment.articleid
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.articleid
     *
     * @param articleid the value for blog_comment.articleid
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.createtime
     *
     * @return the value of blog_comment.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.createtime
     *
     * @param createtime the value for blog_comment.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }
}