package com.jiangKlijna.web.bean

class FollowSubject {
    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_subject.id

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_subject.id

     * @return the value of blog_follow_subject.id
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_subject.id

     * @param id the value for blog_follow_subject.id
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var id: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_subject.fromuser

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_subject.fromuser

     * @return the value of blog_follow_subject.fromuser
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_subject.fromuser

     * @param fromuser the value for blog_follow_subject.fromuser
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var fromuser: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_subject.tosubject

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_subject.tosubject

     * @return the value of blog_follow_subject.tosubject
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_subject.tosubject

     * @param tosubject the value for blog_follow_subject.tosubject
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var tosubject: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_subject.createtime

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_subject.createtime

     * @return the value of blog_follow_subject.createtime
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_subject.createtime

     * @param createtime the value for blog_follow_subject.createtime
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var createtime: Long? = null
}