package com.jiangKlijna.web.bean;

public class FollowUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_user.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_user.fromuser
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer fromuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_user.touser
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer touser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_user.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Long createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_user.id
     *
     * @return the value of blog_follow_user.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_user.id
     *
     * @param id the value for blog_follow_user.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_user.fromuser
     *
     * @return the value of blog_follow_user.fromuser
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getFromuser() {
        return fromuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_user.fromuser
     *
     * @param fromuser the value for blog_follow_user.fromuser
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setFromuser(Integer fromuser) {
        this.fromuser = fromuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_user.touser
     *
     * @return the value of blog_follow_user.touser
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getTouser() {
        return touser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_user.touser
     *
     * @param touser the value for blog_follow_user.touser
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setTouser(Integer touser) {
        this.touser = touser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_user.createtime
     *
     * @return the value of blog_follow_user.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_user.createtime
     *
     * @param createtime the value for blog_follow_user.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }
}