package com.jiangKlijna.web.bean

class FollowUser {
    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_user.id

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_user.id

     * @return the value of blog_follow_user.id
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_user.id

     * @param id the value for blog_follow_user.id
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var id: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_user.fromuser

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_user.fromuser

     * @return the value of blog_follow_user.fromuser
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_user.fromuser

     * @param fromuser the value for blog_follow_user.fromuser
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var fromuser: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_user.touser

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_user.touser

     * @return the value of blog_follow_user.touser
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_user.touser

     * @param touser the value for blog_follow_user.touser
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var touser: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_user.createtime

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_user.createtime

     * @return the value of blog_follow_user.createtime
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_user.createtime

     * @param createtime the value for blog_follow_user.createtime
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var createtime: Long? = null
}