package com.jiangKlijna.web.bean;

public class FollowSubject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_subject.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_subject.fromuser
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer fromuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_subject.tosubject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer tosubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_follow_subject.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Long createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_subject.id
     *
     * @return the value of blog_follow_subject.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_subject.id
     *
     * @param id the value for blog_follow_subject.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_subject.fromuser
     *
     * @return the value of blog_follow_subject.fromuser
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getFromuser() {
        return fromuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_subject.fromuser
     *
     * @param fromuser the value for blog_follow_subject.fromuser
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setFromuser(Integer fromuser) {
        this.fromuser = fromuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_subject.tosubject
     *
     * @return the value of blog_follow_subject.tosubject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getTosubject() {
        return tosubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_subject.tosubject
     *
     * @param tosubject the value for blog_follow_subject.tosubject
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setTosubject(Integer tosubject) {
        this.tosubject = tosubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_follow_subject.createtime
     *
     * @return the value of blog_follow_subject.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_follow_subject.createtime
     *
     * @param createtime the value for blog_follow_subject.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }
}