package com.jiangKlijna.web.bean

class Subject {
    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_subject.id

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_subject.id

     * @return the value of blog_subject.id
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_subject.id

     * @param id the value for blog_subject.id
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var id: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_subject.title

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_subject.title

     * @return the value of blog_subject.title
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_subject.title

     * @param title the value for blog_subject.title
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var title: String? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_subject.createtime

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_subject.createtime

     * @return the value of blog_subject.createtime
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_subject.createtime

     * @param createtime the value for blog_subject.createtime
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var createtime: Long? = null
}