package com.jiangKlijna.web.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.username
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.password
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.avatar
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.numberofwords
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Long numberofwords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    private Long createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.id
     *
     * @return the value of blog_user.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.id
     *
     * @param id the value for blog_user.id
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.username
     *
     * @return the value of blog_user.username
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.username
     *
     * @param username the value for blog_user.username
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.password
     *
     * @return the value of blog_user.password
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.password
     *
     * @param password the value for blog_user.password
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.avatar
     *
     * @return the value of blog_user.avatar
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.avatar
     *
     * @param avatar the value for blog_user.avatar
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.numberofwords
     *
     * @return the value of blog_user.numberofwords
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Long getNumberofwords() {
        return numberofwords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.numberofwords
     *
     * @param numberofwords the value for blog_user.numberofwords
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setNumberofwords(Long numberofwords) {
        this.numberofwords = numberofwords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.createtime
     *
     * @return the value of blog_user.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.createtime
     *
     * @param createtime the value for blog_user.createtime
     *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }
}