package com.jiangKlijna.web.bean

class User {
    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.id

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.id

     * @return the value of blog_user.id
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.id

     * @param id the value for blog_user.id
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var id: Int? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.username

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.username

     * @return the value of blog_user.username
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.username

     * @param username the value for blog_user.username
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var username: String? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.password

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.password

     * @return the value of blog_user.password
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.password

     * @param password the value for blog_user.password
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var password: String? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.avatar

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.avatar

     * @return the value of blog_user.avatar
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.avatar

     * @param avatar the value for blog_user.avatar
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var avatar: String? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.numberofwords

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.numberofwords

     * @return the value of blog_user.numberofwords
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.numberofwords

     * @param numberofwords the value for blog_user.numberofwords
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var numberofwords: Long? = null

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.createtime

     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.createtime

     * @return the value of blog_user.createtime
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.createtime

     * @param createtime the value for blog_user.createtime
     * *
     * *
     * @mbg.generated Tue Jun 13 22:31:48 GMT+08:00 2017
     */
    var createtime: Long? = null
}